spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  level:
    root: INFO
    com.invest: INFO
