-- Supabase CLI `db push` / 로컬 `supabase db reset` 용 (Flyway V1 과 동일 스키마)
-- 운영은 Spring prod + Flyway 로도 동일하게 적용 가능합니다.

create table if not exists public.users (
    id varchar(64) primary key,
    balance numeric(19, 4) not null default 0
);

create table if not exists public.holdings (
    user_id varchar(64) not null references public.users (id) on delete cascade,
    symbol varchar(16) not null,
    quantity numeric(19, 8) not null default 0,
    average_cost numeric(19, 8) not null default 0,
    primary key (user_id, symbol)
);

create table if not exists public.ledger_entries (
    id bigint generated by default as identity primary key,
    user_id varchar(64) not null references public.users (id) on delete cascade,
    type varchar(32) not null,
    symbol varchar(16),
    quantity numeric(19, 8),
    unit_price numeric(19, 8),
    cash_delta numeric(19, 4) not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_ledger_entries_user_created
    on public.ledger_entries (user_id, created_at desc);

alter table public.users enable row level security;
alter table public.holdings enable row level security;
alter table public.ledger_entries enable row level security;
